/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ftlord.telas;

import com.ftlord.controle.ArquivoC;
import com.ftlord.controle.ProdutosC;
import com.ftlord.model.Produtos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * Janela Principal Inteface para o usuário
 *
 * @author LordFabricio
 */
public class Principal extends javax.swing.JFrame {

    private ArrayList<Produtos> listaProdutos = new ArrayList<>();
    private ProdutosC controleP = new ProdutosC();
    private Produtos p = new Produtos();
    private ArquivoC a = new ArquivoC();
    private String salvarAlterar;
    private Integer linha;

    
    public Principal(Produtos prod, ProdutosC prodC){
        this();
        p = prod;
        controleP = prodC;
    }
    /**
     * Construtor do JFrame Creates new form Principal
     */
    public Principal() {
        initComponents();
        carregaP();
        setLocationRelativeTo(null);
        edicaoAreaCad(false);
        salva.setEnabled(false);
        cancela.setEnabled(false);
        exclui.setEnabled(false);
        altera.setEnabled(false);
        tudo.setEnabled(false);
        salvarAlterar = "limpo";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        areaCad = new javax.swing.JPanel();
        pesquisa = new javax.swing.JButton();
        codigoC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tudo = new javax.swing.JButton();
        valorC = new javax.swing.JTextField();
        quantC = new javax.swing.JTextField();
        descC = new javax.swing.JTextField();
        salva = new javax.swing.JButton();
        altera = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        exclui = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        selecionaI = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        areaL = new javax.swing.JPanel();
        senhaC = new javax.swing.JTextField();
        usuarioC = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areaP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        areaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(1).setMinWidth(300);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        areaP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 310));

        getContentPane().add(areaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 850, 350));

        areaCad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        areaCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesquisa.setText("Pesquisa");
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        areaCad.add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        codigoC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        codigoC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoC.setText("CODIGO");
        codigoC.setToolTipText("");
        codigoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoCMouseClicked(evt);
            }
        });
        areaCad.add(codigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 75, 100, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tudo.setLabel("Mostar Todos");
        tudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tudoActionPerformed(evt);
            }
        });
        jPanel1.add(tudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 42, 180, -1));

        areaCad.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 250, 80));

        valorC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        valorC.setText("Valor");
        valorC.setToolTipText("");
        valorC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valorCMouseClicked(evt);
            }
        });
        areaCad.add(valorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 15, 170, -1));

        quantC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        quantC.setText("Quantidade");
        quantC.setToolTipText("");
        quantC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantCMouseClicked(evt);
            }
        });
        areaCad.add(quantC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 15, 170, -1));

        descC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        descC.setText("Descrição");
        descC.setToolTipText("");
        descC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descCMouseClicked(evt);
            }
        });
        areaCad.add(descC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 270, -1));

        salva.setText("Salvar");
        salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaActionPerformed(evt);
            }
        });
        areaCad.add(salva, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        altera.setText("Alterar");
        altera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraActionPerformed(evt);
            }
        });
        areaCad.add(altera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        cancela.setText("Cancelar");
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });
        areaCad.add(cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 120, -1, -1));

        exclui.setText("Excluir");
        exclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiActionPerformed(evt);
            }
        });
        areaCad.add(exclui, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        areaCad.add(novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaCad.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 160, 140));

        selecionaI.setText("Selecionar Imagem");
        selecionaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaIActionPerformed(evt);
            }
        });
        areaCad.add(selecionaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 58, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Cupom Fiscal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        areaCad.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        getContentPane().add(areaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 160));

        areaL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        areaL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senhaC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        senhaC.setText("Senha");
        areaL.add(senhaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 30));

        usuarioC.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        usuarioC.setText("Usuário");
        areaL.add(usuarioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 30));

        confirma.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        confirma.setText("Acesso");
        areaL.add(confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 30));

        getContentPane().add(areaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 400, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaActionPerformed
        if (salvarAlterar.equals("salvar")) {
            this.salvarP();
            salvarAlterar = "limpo";
        } else if (salvarAlterar.equals("alterar")) {
            this.alterarP();
            salvarAlterar = "limpo";
        } else if (salvarAlterar.equals("limpo")) {
            JOptionPane.showMessageDialog(this, "Adicione ou Altere um Produto Antes", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_salvaActionPerformed

    private void excluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiActionPerformed
        linha = this.tabela.getSelectedRow();
        if (linha >= 0) {
            int id = (int) this.tabela.getValueAt(linha, 0);
            if (controleP.escluirPC(id)) {
                this.carregaP();
                limpaAreaCad();
                edicaoAreaCad(false);
                JOptionPane.showMessageDialog(this, "Produto Excluido com Sucesso!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro... ao Excluir", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_excluiActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        salvarAlterar = "salvar";
        edicaoAreaCad(true);
        novo.setEnabled(false);
        exclui.setEnabled(false);
        pesquisa.setEnabled(false);
        altera.setEnabled(false);
        codigoC.setEnabled(false);
        salva.setEnabled(true);
        cancela.setEnabled(true);
        this.descC.selectAll();
        this.descC.requestFocus();
    }//GEN-LAST:event_novoActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        edicaoAreaCad(false);
        salvarAlterar = "limpo";
        tabela.getSelectionModel().clearSelection();
        novo.setEnabled(true);
        exclui.setEnabled(false);
        pesquisa.setEnabled(true);
        altera.setEnabled(false);
        codigoC.setEnabled(true);
        salva.setEnabled(false);
        cancela.setEnabled(false);
        imagem.setIcon(null);
        limpaAreaCad();
    }//GEN-LAST:event_cancelaActionPerformed

    private void alteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraActionPerformed
        String file = descC.getText();
        linha = this.tabela.getSelectedRow();
        if (linha >= 0) {
            salvarAlterar = "alterar";
            edicaoAreaCad(true);
            novo.setEnabled(false);
            exclui.setEnabled(false);
            pesquisa.setEnabled(false);
            altera.setEnabled(false);
            codigoC.setEnabled(false);
            salva.setEnabled(true);
            cancela.setEnabled(true);
            this.descC.setText(p.getDescProduto());
            this.quantC.setText(String.valueOf(p.getQuantProduto()));
            this.valorC.setText(String.valueOf(p.getValorProduto()));
            this.descC.selectAll();
            this.descC.requestFocus();
            try {
                int id = (int) this.tabela.getValueAt(linha, 0);
                p = controleP.pegaPC(id);
                this.descC.setText(p.getDescProduto());
                this.quantC.setText(String.valueOf(p.getQuantProduto()));
                this.valorC.setText(String.valueOf(p.getValorProduto()));
                imagem.setIcon(a.pegaImagem(file = descC.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Selecione Um Registro", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_alteraActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
        if (!"CODIGO".equals(codigoC.getText())) {
            DefaultTableModel tb = (DefaultTableModel) this.tabela.getModel();
            final TableRowSorter<TableModel> classificador = new TableRowSorter<>(tb);
            this.tabela.setRowSorter(classificador);
            String id = this.codigoC.getText();
            classificador.setRowFilter(RowFilter.regexFilter(id, 0));
            this.pesqP();
        } else {
            JOptionPane.showMessageDialog(this, "Digite o Codigo do Produto", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        tudo.setEnabled(true);
        codigoC.setText("CODIGO");
    }//GEN-LAST:event_pesquisaActionPerformed

    private void selecionaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaIActionPerformed
        if (!"Descrição".equals(descC.getText())) {
            imagem.setIcon(a.salvarImagem(descC.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Informe a Descrição");
        }
    }//GEN-LAST:event_selecionaIActionPerformed

    private void codigoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoCMouseClicked
        codigoC.selectAll();
    }//GEN-LAST:event_codigoCMouseClicked

    private void descCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descCMouseClicked
        descC.selectAll();
    }//GEN-LAST:event_descCMouseClicked

    private void quantCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantCMouseClicked
        quantC.selectAll();
    }//GEN-LAST:event_quantCMouseClicked

    private void valorCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorCMouseClicked
        valorC.selectAll();
    }//GEN-LAST:event_valorCMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        exclui.setEnabled(true);
        altera.setEnabled(true);
    }//GEN-LAST:event_tabelaMouseClicked

    private void tudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tudoActionPerformed
        codigoC.setText("");
        if ("".equals(codigoC.getText())) {
            DefaultTableModel tb = (DefaultTableModel) this.tabela.getModel();
            final TableRowSorter<TableModel> classificador = new TableRowSorter<>(tb);
            this.tabela.setRowSorter(classificador);
            String id = this.codigoC.getText();
            classificador.setRowFilter(RowFilter.regexFilter(id, 0));
            this.pesqP();
        } else {
            JOptionPane.showMessageDialog(this, "Digite o Codigo do Produto", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        tudo.setEnabled(false);
        codigoC.setText("CODIGO");
    }//GEN-LAST:event_tudoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controleP.pegaPC(11);
        System.out.println(p.getDescProduto());
        Cupom c = new Cupom(p, controleP);
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Metodo MAIN responsavel por Iniciar a Aplicação
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    /**
     * Metodo que Ordena a Pesquisa de UM unico Produto
     */
    private void pesqP() {
        try {
            int id = (int) this.tabela.getValueAt(0, 0);
            p = controleP.pegaPC(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Produto Não Encontrado", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * Metodo que Ordena Salvar o Produto no Banco de Dados
     */
    private void salvarP() {
        p.setDescProduto(this.descC.getText());
        p.setQuantProduto(Double.parseDouble(this.quantC.getText()));
        p.setValorProduto(Double.parseDouble(this.valorC.getText()));
        if (controleP.salvarPC(p) > 0) {
            this.carregaP();
            limpaAreaCad();
            edicaoAreaCad(false);
            imagem.setIcon(null);
            JOptionPane.showMessageDialog(this, "Cadastro Realizado com Sucesso!!!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro... ao Cadastrar", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Metodo que Ordena Alterar o Produto no Banco de Dados
     */
    private void alterarP() {
        p.setDescProduto(this.descC.getText());
        p.setQuantProduto(Double.parseDouble(this.quantC.getText()));
        p.setValorProduto(Double.parseDouble(this.valorC.getText()));
        if (controleP.alterarPC(p)) {
            this.carregaP();
            limpaAreaCad();
            edicaoAreaCad(false);
            imagem.setIcon(null);
            JOptionPane.showMessageDialog(this, "Alteração Realizada com Sucesso!!!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro... ao Alterar", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Metodo que Ordena Carreagar em uma LISTA os Produtos do Banco de Dados
     */
    private void carregaP() {
        listaProdutos = controleP.listaPC();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        int cont = listaProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaProdutos.get(i).getIdProduto(),
                listaProdutos.get(i).getDescProduto(),
                listaProdutos.get(i).getQuantProduto(),
                listaProdutos.get(i).getValorProduto()
            });
        }
    }

    /**
     * Metodo de Controle da Janela Principal para Evitar Redundâncias
     *
     * @param c
     */
    private void edicaoAreaCad(boolean c) {
        this.descC.setEnabled(c);
        this.quantC.setEnabled(c);
        this.valorC.setEnabled(c);
        this.selecionaI.setEnabled(c);
    }

    /**
     * Metodo de Controle da Janela Principal para Evitar Redundâncias
     */
    private void limpaAreaCad() {
        this.descC.setText("Descrição");
        this.quantC.setText("Quantidade");
        this.valorC.setText("Valor");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altera;
    private javax.swing.JPanel areaCad;
    private javax.swing.JPanel areaL;
    private javax.swing.JPanel areaP;
    private javax.swing.JButton cancela;
    private javax.swing.JTextField codigoC;
    private javax.swing.JButton confirma;
    private javax.swing.JTextField descC;
    private javax.swing.JButton exclui;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    private javax.swing.JButton pesquisa;
    private javax.swing.JTextField quantC;
    private javax.swing.JButton salva;
    private javax.swing.JButton selecionaI;
    private javax.swing.JTextField senhaC;
    private javax.swing.JTable tabela;
    private javax.swing.JButton tudo;
    private javax.swing.JTextField usuarioC;
    private javax.swing.JTextField valorC;
    // End of variables declaration//GEN-END:variables
}
